export const providers = [
  'LuxLite',
  'Космонова',
  'Воля Бізнес',
  'UTELS',
  'Kyivlink',
  'Nika Network',
  'Коло.ТБ',
  'ВОЛЯ',
  'Coolnet',
  'SimNet',
  'НАШНЕТ',
  'Looknet',
  'IPnet',
  'Apelsin.Net ',
  'LAN TRACE',
  'Квик.Нет',
  'Київстар Домашній Інтернет',
  'ХАТАНЕТ',
  'MyLink',
  'Волинські Оптичні Мережі',
  'КУЗЯ',
  'АЙОЛ НЕТ',
  'ФРІНЕТ',
  'Corbina Telecom',
  'L4.ua',
  'LocalNet',
  'NEMIcom',
  'Undernet',
  'Unlimnet',
  'Vechir',
  'Vega',
  'Vodafone Gigabit Net',
  'Домашня Мережа ТМ',
  'ДОМОНЕТ',
  'Свард',
  'СІТІЛАН',
  'Maximum Net',
  'Адамант Телеком',
  'Місто-ТВ',
  'Bilink',
  'Flycom',
  'TELZA',
  'UA GROUP',
  'Телком',
  'Granat',
  'HomeNet.IT',
  'Malex',
  'Network.lviv.ua',
  'PitLine',
  'Sinet',
  'SOTKA.NET',
  'Xnet',
  'БиДжиНет',
  'ВОЛЗ',
  'Застава.net',
  'Макснет',
  'TIM',
  '4 SEASONS',
  'DiaNet',
  'EuroLink',
  'Kichkas.NET',
  'Колумбус',
  'Кристалл Телеком',
  'НВП-Коннект',
  'EASTNET',
  'ICORP.NET',
  'Драйв',
  'Rubintele.com',
  'Teremki@LAN',
  'Паутина',
  'opticom-plus',
  '3NET',
  'Boryspil.Net',
  'Cactus',
  'Etherlink',
  'Gepard',
  'GPON',
  'IMC',
  'ISP Alternativa',
  'ITKOM',
  'KievNet',
  'Linkcom',
  'Net-City',
  'Radionet',
  'SANNET.DN.UA',
  'Інфоаура',
  'Украинская интернет компания',
  'Фрегат',
  'Baryshivka.NET',
  'Cubic-Tech',
  'Globalnet',
  'SKIF',
  'SunNet',
  'Уарнет',
  'CNM',
  'FiberNet',
  'ШаломТелеком',
  'Sk-Net',
  'Wlink',
  'Darnytsia.Net',
  'Happy.net.ua',
  'ISP OnLine',
  'MTTM',
  'Lcom',
  'SkyNET Telecom',
  'SOHONET',
  'Znet',
  'Сітел',
  'Alfa-Link',
  'CatNet Telecom',
  'SmartNET',
  'АРС -Телекомпания',
  'ЛИКОНЕТ',
  'Союз Телеком',
  'OptoLAN',
  'Vizitnet',
  'DisNet',
  'DreamNET',
  'WiMAX-Украина',
  'Котовские Интернет Сети',
  'Юнионком',
  'GreeNet',
  'TODOR',
  'Телегруп',
  'ФАУСТ',
  'ChokolovkaNET',
  'CrazyNetwork',
  'LIMANET',
  'Наш Простір',
  'ООО Регион Телеком',
  'Стар Телеком',
  'Brovis',
  'MIIT',
  'ДатаНет',
  'Zurbagan',
  'ИнфоСвязь',
  'ІНТРАФІК',
  'Технологии Онлайн',
  'Veles IPS',
  'КОМІТЕХ',
  'Fastlan technology',
  'LANGATE',
  'Batyevka.NET',
  'Укртелеком',
  '4G Star',
  'UNTC ',
  'Vodafone',
  'Інтертелеком',
  'Київстар GSM',
  'Череда',
  'Silver Telecom',
  'BLESS',
  'ТК ПЛАЗМА',
  'Гіпернет',
  'Нетгруп',
  'AirNet Карловка',
  'FCOM',
  'Green.net',
  'Вінастеріск',
  'Winet Шепетівка',
  'УкрКом',
  'ЕкстраТел',
  'Link Telecom Service',
  'ЄВРОЛАЙН-УКРАЇНА',
  'ТТІ України',
  'LissNet',
  'HappyNet',
  'ІнфоДом',
  'X-MY.NET',
  '911NET',
  'Unetco',
  'Sanaplus Group',
  'Трінет',
  'LANCOM Новоукраїнка',
  'Xlan',
  'ТЕХНООПТИК',
  'STING',
  'ТРК "Майбуття"',
  'Alpha',
  'Ваш Інтернет',
  'netmix',
  'Диалог',
  'Харків Онлайн',
  'БКМ',
  'КРАЙ-НЕТ',
  'Метротелеком',
  'САТок',
  'ОЛЛИ ТРАНС',
  'xCLOUD',
  'Норма-4',
  'MyNet',
  'Airexpress',
  'СКАЙНЕТ Запоріжжя',
  'Хомлінк',
  'Даталайн',
  '3D Com',
  'Mukachevo Online',
  'Планета-Юг',
  'Овруч.Net',
  'Domnet',
  'ITnet',
  'KamNetUa',
  'ExpertNet',
  'Winet Ужгород',
  'VISP',
  'Uline',
  'Trans Digital',
  'Swessa-net',
  'SVT-com',
  'STSNet',
  'Starnet Павлоград',
  'Starnet Луцьк',
  'Skynetlan',
  'Satellite Славянск',
  'Satellite Service',
  'Rivne ISP',
  'Prolvl',
  'Popelnya net',
  'Online Дніпро',
  'Omega Group',
  'Octonet',
  'neXus',
  'Newnet',
  'NeoNet',
  'NCN',
  'Naknet',
  'Multinet',
  'Meganet',
  'MatrixNet',
  'Magicom',
  'M-tel',
  'Krolevets',
  'Korsi',
  'Jamzo',
  'Он лайн Коростень',
  'ІТ люкс',
  'Золотоноша on-line',
  'Битек Телеком',
  'Freeway',
  'ХомНет',
  'Quadronet',
  'ULAN ISP',
  'Vitelecom',
  'ISP HLink',
  'Мій провайдер',
  'SkyNet Ізмаїл',
  'Голта',
  'Ван Телеком',
  'Западная мультисервисная сеть',
  'LanplusNet',
  'Ірпінькомунікаціясервіс',
  'ISTEC',
  'ІТЛ',
  'ЦСО',
  'UIP',
  'СкайСтрім',
  'Internet Балта',
  'КАНКОМ',
  'Mediana-plus',
  'Дикий Сад',
  'ІНТС',
  'SMARTCOM',
  'В.О.К.С',
  'Instal telecom',
  'Infobyte',
  'Info-centr',
  'Imperial',
  'Home net Первомайський',
  'GLN',
  'Gigabit-net',
  'Fiberlink',
  'Eurocomputer',
  'Epsilon',
  'Elitnet',
  'Drive internet',
  'Dinasnet',
  'Cyberlan',
  'Citynet Світловодськ',
  'City Link',
  'Bitnet',
  'Belicom',
  'Belcom',
  'Avenue',
  'Artmedia',
  'Aida',
  'Agrocom',
  'Центр.net',
  'Хост',
  'Хата net Запоріжжя',
  'Укрсат',
  'ТРК Ідеал',
  'ТРК Глухів',
  'ТОБІ',
  'ТІМ Умань',
  'Суми online',
  'Спайдернет',
  'Прокк',
  'Основа',
  'НТ-сервіс',
  'Маеток',
  'Леотел',
  'КІТ',
  'Зеніт',
  'Діалект',
  'Дельта',
  'ДВС-САТ',
  'Гранд Телеком',
  'Гольфстрім',
  'ГОК',
  'Візит',
  'Ведекон',
  'Ваш нет',
  'БІТ',
  'Атлас',
  'Амрон',
  'Аскон',
  'Самарь',
  'Сандра',
  'МТМ',
  'Днепронет',
  'Sunline-ua',
  'CDC',
  'OptiCom',
  'Крам',
  'RUDAKI.NET',
  'Performance',
  'Inter-Kam',
  'SvalyavaNET',
  'Forsage',
  'BFG-Net',
  'Onet',
  'Intercom-online',
  'Глухів-500',
  'Limnet',
  'Expres Виноградов',
  'Rlan',
  'Syndicate',
  'Win telecom',
  'Master Net',
  'XAT NET',
  'Сетілайт',
  'УЖНЕТ',
  'UANET',
  'AlDen',
  'Express',
  'QNET',
  'Gaziknet',
  'likenet',
  'skystar',
  'Megalan+',
  'IPLink',
  'Brnet',
  'Neocom',
  'Netstar',
  'Global-net',
  'PrideTele',
  'Umbrella',
  'Sky-link',
  'HomeNetSumy',
  'Opticline',
  'PSTS Net',
  'КУБ-Телеком',
  'Центр Телеком',
  'Darkwood',
  'ОбухівNet',
  'Skynet Бровари',
  'Milan Network',
  'Inttel',
  'KULINICHI.NET',
  'FastNET',
  'Орбита-ТВ',
  'KIM',
  'Mirtelecom',
  'ХотинНет',
  'Camelot',
  'Чугуевские компьютерные сети',
  'Bestlink',
  'Dks компьютерная сеть',
  'Wenet',
  'Nicenet',
  'E-net',
  'svs',
  'Esphil',
  'Skyline',
  'Energy.net',
  'Malta',
  'Telelan',
  'Civilization',
  'Bravoport',
  'Belnet',
  'Ekta',
  'S-host',
  'Інфомір',
  'BLC',
  'Powernet',
  'Altanet',
  'Novaline',
  'Slink',
  'Astratelecom',
  'Luxnet',
  'PretcherNet',
  'Tvin',
  'Real-Net',
  'ISP Energy',
  'FLIPNET',
  'Groza',
  'Аватар',
  'Linknet',
  'Belgorod-Net',
  'Aist',
  'Soborka net',
  'Unitel',
  'Північ Лайн',
  'VAK',
  'IT-mark',
  'Мир высоких скоростей',
  'Ринет',
  'Proline',
  'Велтон Телеком',
  'Elite-Line',
  'LANpro',
  'Intelekt',
  'ДІМ-Інтернет',
  'kopiyka',
  'EuroNet',
  'LuxLink',
  'ExStreamNet',
  'DSLine',
  'Діскавері',
  'UTeam',
  'SITV',
  'SKM Network',
  '16x',
  'Supernet',
  'Klad',
  'TKS',
  'Vinfast',
  'ZasNet',
  'ЧП Захарьев',
  'Еверест',
  'Винер телеком',
  'X-COM',
  'Total-Net',
  'INFONET',
  'Нова-Сервис',
  'WEST NETWORK',
  'Гигабит',
  'LanCity',
  'GiZ-NeT',
  'KTM',
  'PollyComm',
  'Цифрові рішення',
  'Елітон',
  'Dominet',
  'Диамант-тв',
  'City-Net',
  'Westelecom',
  'МЕГАПРОСТИР',
  'STRIM',
  'АТВ ПЛЮС',
  'ХОУМ-НЕТ',
  'Smela@NET',
  'Галактика',
  'Disavi Line',
  'Веко',
  'Avator',
  'OBL-NET',
  'Нім-Нет',
  'Fobos',
  'Thebest-on',
  'Intelesi',
  'Пленет',
  'Трилоджик груп',
  'Eurolan',
  'Kremenets WDS',
  'АСТРА',
  'Albion',
  'T-lion.net',
  'Freeline',
  'BIGNET',
  'Харнет',
  'Malink.net.ua',
  'Flagman',
  'NashNET Рівне',
  'Kahovka.Net',
  'NET-IP',
  'Hotlan',
  'Wi-com',
  'ДНЕПРОЛИНК',
  'ТРК Лебедин',
  '5-Stars',
  'Т-Лайн',
  'WebService',
  'ГІГАТЕЛ',
  'WestNet',
  'LanComNet',
  'MegaNet',
  'Bilberry',
  'StreamNetwork',
  'Radionetwork',
  'X-CITY',
  'DTS',
  'INI.NET',
  'cool-net',
  'Vica-TV',
  'Xbyte',
  'VIPLan',
  'SunLine',
  'Lucky.Net',
  'Rusanovka-net',
  'Orion city',
  'NETLINK',
  'ХОУМНЕТ Київ',
  'DeltaNet',
  'BerLine',
  'КВАНТ',
  'newEDGE',
  'ДКМ',
  'Сетка',
  'SISTEC',
  'RostNet',
  '10G',
  'McLaut',
  'PRO100NET',
  'Sudafone',
  'ТРК ТВ-Ком',
  'ЛАННЕТ - Львів',
  'Комкор Сервіс',
  'FTC',
  'X-NET',
  'SkyNet Калуш',
  'Altairline',
  'Linet',
  'UAProstir',
  'Мирател',
  'Microcom',
  'НБІ',
  'ArsLAN',
  'Optinet',
  'ACCESS.NET.UA',
  'Uacity',
  'Астра Юг Телеком',
  'Khust.com.ua',
  'ITCentre',
  'MediaMAX',
  'ISP Shtorm',
  'StarLine',
  'ТВ-НЕТ',
  'Радиолинк',
  'Микснет',
  'Українські Оптичні Системи',
  'Ukrlink',
  'Kievline',
  'i-link',
  'Хутко',
  'ICN',
  'JetNet',
  'Golden Net',
  'TERNET',
];
